### ISSUE TITLE
Enhance SOF driver support for HDAudio on SKL+ platforms

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#137]
This will include a group of features
- [x] Enable SOF driver to support 3rd party HD-A analog codec. #135 
- [x] Enable SOF driver to support DP MST (DisplayPort's Multi-stream transport) #136 
- [ ] Enable SOF driver to support legacy HD-A mode #138
- [x] Enable DPIB/posbuf pointer mode for SKL+ platforms #122

It cannot refer to issues in SOF repo now.

**Comment by mengdonglin** [comment]
@keyonjie Actually, these features are what you've already been working on or planned. 

#137 is the parent (Epic) of a group of features and I'm trying to use Zenhub to provide more structured issue/PR management, which can apply to both new features and bugs. 

I hope the new Zenhub project board could be more helpful for us.

**Comment by plbossart** [comment]
@mengdonglin we should close this issue, most topics are fixed now or were closed.

**Comment by wenqingfu** [comment]
Except #138, others were addressed. it's an open if we need #138 eventually or not, so close this one umbrella issue tracker for now.

**Comment by plbossart** [comment]
It's really the other way around. If we had started with #138, we could have unified legacy and SOF drivers, and test HDaudio with and without DSP. But of course that's not what was done so we have two drivers to maintain :-1: And I forget that we have to solve the dynamic detection of which driver to use on which platform, last time we tried it broke Linus' laptop. yay.

**Comment by wenqingfu** [comment]
Won't that duplicate code in SOF with legacy HDAudio driver? We cannot really obsolete the "world best driver" in terms of working across generations and various company products.

**Comment by plbossart** [comment]
There is a lot of duplication already, e.g. for HDMI support, we didn't even try to simplify things and the argument that the legacy driver is the 'world best' is only a matter of reference point...
