### ISSUE TITLE
Voice Trigger feature set

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#594]
This feature set includes these sub-tasks:

- [ ] Voice Trigger: enable component channel selector  https://github.com/thesofproject/linux/issues/574
- [x] IPC: enable larger data messages https://github.com/thesofproject/linux/issues/575
- [ ] Voice Trigger: enable async/unsolicited notification https://github.com/thesofproject/linux/issues/576
- [ ] PM: enable D0i1 support https://github.com/thesofproject/linux/issues/577

**Comment by dbaluta** [comment]
Silly question: what is the difference between Voice Activity Detection and Voice trigger? Is there any plan to add Voice Activity Detection in SOF?

**Comment by plbossart** [comment]
> Silly question: what is the difference between Voice Activity 
> Detection and Voice trigger?
>
Voice Trigger (rather Sound Trigger to use Android parlance) can include 
keyword detection and providing a 2s buffer for apps (local or cloud) to 
double-check.

VAD would be what you have in your PDM block on i.MX (comment based on 
patches shared on alsa-devel)

**Comment by dbaluta** [comment]
So, the question is now can we create a common infrastructure for both VAD and Voice Trigger?

I mean the infrastructure for signalling when voice is detected Or keyword is detected.

**Comment by plbossart** [comment]
On 1/28/19 2:56 PM, Daniel Baluta wrote:
>
> So, the question is now can we create a common infrastructure for both 
> VAD and Voice Trigger?
>
> I mean the infrastructure for signalling when voice is detected Or 
> keyword is detected.
>
that's the goal (same as in Android btw). The intent is that the kernel 
knows absolutely nothing about what happens in the firmware and just 
handles an opaque notification from the DSP with a bunch of data which 
can be parsed/interpreted only at the application and firmware levels.
>

**Comment by dbaluta** [comment]
@plbossart great!

Do you have some open source algorithms for voice trigger? Or just something custom?

**Comment by plbossart** [comment]
> Do you have some open source algorithms for voice trigger? Or just 
> something custom?
>
We will probably have an example for e.g. simple VAD or even level 
detector, mainly for tests.

A more complex solution (Alexa and friends) is likely out-of-scope, this 
is the type of secret sauce that 3rd parties or OEMs want to keep 
control on - and that's alright with SOF, we have a permissive license 
precisely so that people who have parts they don't want to share can 
still make products.

**Comment by plbossart** [comment]
@mengdonglin this looks complete, no? can we close?

**Comment by lgirdwood** [comment]
@mengdonglin can you tag this to a milestone.

**Comment by plbossart** [comment]
closing since no information provided
