### ISSUE TITLE
Harden APL/GLK hardware support

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#87]
The current driver does not implement all the recommended hardware setups
- [x] 1. firmware download needs to be retried 
- [x] 2. #776 power-gating and clock gating needs to be disabled during firmware download
- [x] 3. some bits are not reprogrammed on resume
- [ ] 4. watchdog and recovery needed
- [x] 5. #777 delays after programming registers (and/or loops to check status changes)
- [x] 6. #778 set I2S as slave before enabling DSP
- [ ] 7. avoid DMA resume capability on capture

Adding a blanket bug to cover all these improvements. Filed as a bug since the current code is not robust enough.

**Comment by mengdonglin** [comment]
This is an enhancement, so change label from bug to 'enhancement', still P2 to get attention.

**Comment by ranj063** [comment]
> The current driver does not implement all the recommended hardware setups
> 
> * [x]  1. firmware download needs to be retried
> * [ ]  2. power-gating and clock gating needs to be disabled during firmware download
> * [x]  3. some bits are not reprogrammed on resume
> * [ ]  4. watchdog and recovery needed
> * [ ]  5. delays after programming registers (and/or loops to check status changes)
> * [ ]  6. set I2S as slave before enabling DSP
> * [ ]  7. avoid DMA resume capability on capture
> 
> Adding a blanket bug to cover all these improvements. Filed as a bug since the current code is not robust enough.
@mengdonglin  the ones that I checked are already done

**Comment by plbossart** [comment]
@wenqingfu can we get someone assigned to this? We know our programming sequences don't fully follow recommended guidelines, let's fix those known opens, at least the opens 2, 5, 6 and keep watchdog/recovery and DAM resume capability aside.

**Comment by plbossart** [comment]
@zhuyingjiang can you clarify what remains to be done for this issue?

**Comment by zhuyingjiang** [comment]
@plbossart The remains are:
4. watchdog and recovery needed
7. avoid DMA resume capability on capture

The  5. #777 delays after programming registers (and/or loops to check status changes)
is almost been done after my PR #1020 #997 is merged.
Still there may need one more PR for "set DUM bit on device power up"

**Comment by plbossart** [comment]
we are not going to support DMA resume, so forking the firmware recovery as a separate issue https://github.com/thesofproject/linux/issues/1675
